import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://gqlcxvukyezqpdftjdeo.supabase.co','sb_publishable_ViHQ2SZREPXE_GCrN_zDrw__kXoN9D8');
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const slug=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').slice(0,90);
const style=document.createElement('style');style.textContent=`.odo-journal-admin{margin:40px 0;border-top:1px solid rgba(245,241,232,.08);padding-top:35px}.journal-admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.journal-admin-card{border:1px solid rgba(200,165,96,.2);background:#0d0d0c;padding:22px}.journal-admin-card h3{margin-top:0}.journal-admin-form{display:grid;gap:10px}.journal-admin-form label{display:grid;gap:6px;color:#888;font-size:.55rem;letter-spacing:.12em;text-transform:uppercase}.journal-admin-form input,.journal-admin-form textarea,.journal-admin-form select{background:#080808;color:#fff;border:1px solid #37342f;padding:11px}.journal-admin-form textarea{min-height:140px}.journal-admin-post{border-top:1px solid rgba(245,241,232,.08);padding:12px 0;display:flex;justify-content:space-between;gap:14px}.journal-admin-post small{color:#777}.journal-admin-post button{background:#111;color:#f5f1e8;border:1px solid #39362f;padding:7px 10px;cursor:pointer}.journal-admin-post .publish{color:#e5c982}@media(max-width:900px){.journal-admin-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
async function mount(){const main=$('.odo-admin-main');if(!main||document.getElementById('odoJournalAdmin'))return;const {data:{session}}=await supabase.auth.getSession();if(!session)return;const {data:me}=await supabase.from('profiles').select('is_admin').eq('id',session.user.id).maybeSingle();if(!me?.is_admin)return;const sec=document.createElement('section');sec.id='odoJournalAdmin';sec.className='odo-journal-admin';sec.innerHTML=`<div class="odo-admin-title"><div><p class="eyebrow">CONTENT</p><h2>JOURNAL.</h2></div><p>Publish ODOFASHION news, drop announcements and GREATODOUNIVERSE stories directly from admin.</p></div><div class="journal-admin-grid"><div class="journal-admin-card"><h3>NEW STORY</h3><form id="journalForm" class="journal-admin-form"><label>Title<input name="title" required placeholder="e.g. ODO First Drop Is Here"></label><label>Category<select name="category"><option>NEWS</option><option>DROP</option><option>UPDATE</option><option>BEHIND THE SCENES</option><option>GREATODOUNIVERSE</option></select></label><label>Excerpt<input name="excerpt" placeholder="Short description"></label><label>Cover image URL<input name="cover_image_url" placeholder="https://..."></label><label>Content<textarea name="content" required placeholder="Write the story..."></textarea></label><label><input style="width:auto" type="checkbox" name="published"> Publish immediately</label><button class="checkout-submit" type="submit">SAVE STORY →</button><div id="journalMessage" class="odo-message"></div></form></div><div class="journal-admin-card"><h3>STORIES</h3><div id="journalPosts">Loading…</div></div></div>`;main.appendChild(sec);sec.querySelector('#journalForm').onsubmit=save;await refreshPosts()}
async function save(e){e.preventDefault();const f=new FormData(e.currentTarget);const title=String(f.get('title')).trim(), category=String(f.get('category')), published=f.get('published')==='on';const row={title,slug:slug(title),category,excerpt:String(f.get('excerpt')||'').trim(),content:String(f.get('content')||''),cover_image_url:String(f.get('cover_image_url')||'').trim()||null,published,published_at:published?new Date().toISOString():null,created_by:(await supabase.auth.getUser()).data.user?.id};const {error}=await supabase.from('journal_posts').insert(row);$('#journalMessage').textContent=error?error.message:'Story saved.';if(!error){e.currentTarget.reset();await refreshPosts()}}
async function refreshPosts(){const box=$('#journalPosts');if(!box)return;const {data,error}=await supabase.from('journal_posts').select('id,title,category,published,published_at,created_at').order('created_at',{ascending:false}).limit(30);if(error){box.textContent=error.message;return}box.innerHTML=data?.length?data.map(p=>`<div class="journal-admin-post"><div><strong>${esc(p.title)}</strong><br><small>${esc(p.category)} · ${p.published?'PUBLISHED':'DRAFT'}</small></div><div><button data-publish="${p.id}" class="publish">${p.published?'UNPUBLISH':'PUBLISH'}</button><button data-delete="${p.id}">DELETE</button></div></div>`).join(''):'<div class="customer-note">No stories yet.</div>';box.querySelectorAll('[data-publish]').forEach(b=>b.onclick=async()=>{const id=b.dataset.publish;const current=data.find(x=>x.id===id);await supabase.from('journal_posts').update({published:!current.published,published_at:!current.published?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id);await refreshPosts()});box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this story?'))return;await supabase.from('journal_posts').delete().eq('id',b.dataset.delete);await refreshPosts()})}
mount();
