import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://gqlcxvukyezqpdftjdeo.supabase.co','sb_publishable_ViHQ2SZREPXE_GCrN_zDrw__kXoN9D8');
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const slug=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').slice(0,90);
const styles=document.createElement('style');styles.textContent=`
.odo-journal{padding:70px 0;border-top:1px solid rgba(245,241,232,.08)}.odo-journal-head{display:flex;justify-content:space-between;gap:30px;align-items:end;margin-bottom:30px}.odo-journal-head h2{font-size:clamp(3rem,7vw,6rem);line-height:.86;margin:0}.odo-journal-head p{max-width:500px;color:#77736c;font-size:.72rem;line-height:1.7}.journal-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.journal-card{border:1px solid rgba(245,241,232,.1);background:#0d0d0c;overflow:hidden}.journal-cover{aspect-ratio:16/10;background:#171715;display:flex;align-items:end;padding:18px}.journal-cover img{width:100%;height:100%;object-fit:cover;margin:-18px;max-width:calc(100% + 36px);max-height:calc(100% + 36px)}.journal-meta{padding:20px}.journal-meta small{color:#c8a560;letter-spacing:.14em;font-size:.48rem}.journal-meta h3{font-size:1.4rem;margin:10px 0}.journal-meta p{color:#999;font-size:.68rem;line-height:1.65}.journal-read{display:inline-block;margin-top:12px;color:#f5f1e8;font-size:.54rem;letter-spacing:.12em;text-decoration:none}.journal-empty{border:1px dashed rgba(200,165,96,.25);padding:40px;color:#77736c}.journal-modal{position:fixed;inset:0;z-index:300;background:rgba(0,0,0,.88);display:none;align-items:center;justify-content:center;padding:20px}.journal-modal.open{display:flex}.journal-modal-card{width:min(920px,100%);max-height:90vh;overflow:auto;background:#0b0b0a;border:1px solid rgba(200,165,96,.3);padding:32px;position:relative}.journal-modal-card h2{font-size:clamp(2rem,5vw,4rem);margin:8px 0 16px}.journal-modal-content{color:#b7b1a5;line-height:1.8;font-size:.82rem}.journal-modal-close{position:absolute;right:18px;top:10px;background:none;border:0;color:#f5f1e8;font-size:2rem;cursor:pointer}@media(max-width:900px){.journal-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.journal-head{align-items:flex-start;flex-direction:column}.journal-grid{grid-template-columns:1fr}}
`;
document.head.appendChild(styles);
function mountJournal(){const contact=$('#contact');if(!contact||$('#odoJournal'))return;const sec=document.createElement('section');sec.id='odoJournal';sec.className='section odo-journal';sec.innerHTML=`<div class="odo-journal-head"><div><p class="eyebrow">JOURNAL / NEWS / UPDATES</p><h2>THE ODO<br><em>JOURNAL.</em></h2></div><p>Stories, launches, behind-the-scenes moments and updates from ODOFASHION and GREATODOUNIVERSE.</p></div><div id="journalGrid" class="journal-grid"><div class="journal-empty">Loading the latest ODO stories…</div></div>`;contact.parentNode.insertBefore(sec,contact);}
function openPost(p){let m=$('#odoJournalModal');if(!m){m=document.createElement('div');m.id='odoJournalModal';m.className='journal-modal';m.innerHTML='<div class="journal-modal-card"><button class="journal-modal-close">×</button><div id="journalModalBody"></div></div>';document.body.appendChild(m);m.querySelector('.journal-modal-close').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')}}m.querySelector('#journalModalBody').innerHTML=`<p class="eyebrow">${esc(p.category)} · ${p.published_at?new Date(p.published_at).toLocaleDateString('en-NP'):''}</p><h2>${esc(p.title)}</h2>${p.cover_image_url?`<img src="${esc(p.cover_image_url)}" alt="" style="width:100%;max-height:420px;object-fit:cover;margin:12px 0 24px">`:''}<div class="journal-modal-content">${String(p.content||'').replace(/\n/g,'<br>')}</div>`;m.classList.add('open')}
async function loadPosts(){mountJournal();const {data,error}=await supabase.from('journal_posts').select('id,title,slug,category,excerpt,content,cover_image_url,published,published_at').eq('published',true).order('published_at',{ascending:false}).limit(9);const grid=$('#journalGrid');if(!grid)return;if(error){grid.innerHTML='<div class="journal-empty">Journal is preparing. Check back soon.</div>';return}if(!data?.length){grid.innerHTML='<div class="journal-empty">The first ODO Journal story is coming soon.</div>';return}grid.innerHTML=data.map(p=>`<article class="journal-card"><div class="journal-cover">${p.cover_image_url?`<img src="${esc(p.cover_image_url)}" alt="${esc(p.title)}" loading="lazy">`:''}</div><div class="journal-meta"><small>${esc(p.category)} · ${p.published_at?new Date(p.published_at).toLocaleDateString('en-NP'):''}</small><h3>${esc(p.title)}</h3><p>${esc(p.excerpt||'')}</p><a href="#" class="journal-read" data-id="${p.id}">READ STORY →</a></div></article>`).join('');grid.querySelectorAll('[data-id]').forEach(a=>a.onclick=e=>{e.preventDefault();const p=data.find(x=>x.id===a.dataset.id);if(p)openPost(p)})}
loadPosts();
