import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const sb=createClient('https://gqlcxvukyezqpdftjdeo.supabase.co','sb_publishable_ViHQ2SZREPXE_GCrN_zDrw__kXoN9D8');
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const stars=n=>'★★★★★'.slice(0,Number(n)||0)+'☆☆☆☆☆'.slice(0,5-(Number(n)||0));
const money=v=>`NPR ${Number(v||0).toLocaleString('en-NP')}`;
function styles(){if(document.getElementById('odoReviewStyles'))return;const s=document.createElement('style');s.id='odoReviewStyles';s.textContent=`.odo-reviews{margin-top:24px;padding-top:18px;border-top:1px solid rgba(245,241,232,.08)}.odo-review-summary{display:flex;gap:16px;align-items:center;flex-wrap:wrap}.odo-review-stars{color:#c8a560;letter-spacing:.08em}.odo-review-count{color:#77736c;font-size:.58rem}.odo-review-list{display:grid;gap:10px;margin-top:14px}.odo-review{border:1px solid rgba(245,241,232,.08);padding:13px;background:#0d0d0c}.odo-review-head{display:flex;justify-content:space-between;gap:10px}.odo-review-name{color:#f5f1e8;font-size:.62rem}.odo-review-verified{color:#c8a560;font-size:.48rem;text-transform:uppercase;letter-spacing:.08em}.odo-review-text{color:#aaa;font-size:.64rem;line-height:1.7;margin-top:8px}.odo-review-form{margin-top:15px;padding:14px;border:1px solid rgba(200,165,96,.2);background:#0b0b0a}.odo-review-form select,.odo-review-form textarea{width:100%;background:#111;color:#f5f1e8;border:1px solid rgba(245,241,232,.14);padding:10px;margin-top:7px}.odo-review-form textarea{min-height:90px}.odo-review-btn{margin-top:10px;border:1px solid rgba(200,165,96,.4);background:transparent;color:#f5f1e8;padding:9px 12px;font-size:.54rem;letter-spacing:.08em;cursor:pointer}.odo-review-btn:hover{background:#f5f1e8;color:#080808}.odo-review-note{color:#77736c;font-size:.54rem;line-height:1.6;margin-top:8px}`;document.head.appendChild(s)}
function mount(card,p){if(card.querySelector('.odo-reviews'))return;const wrap=document.createElement('div');wrap.className='odo-reviews';wrap.innerHTML=`<div class="odo-review-summary"><span class="odo-review-stars">Loading…</span><span class="odo-review-count"></span></div><div class="odo-review-list"></div><div class="odo-review-form"><strong style="font-size:.66rem">CUSTOMER REVIEW</strong><div class="odo-review-note">Reviews are available to customers who have received an ODO order. Every review is checked before it appears publicly.</div></div>`;card.appendChild(wrap);load(wrap,p)}
async function load(w,p){const {data:reviews}=await sb.from('product_reviews').select('rating,review_text,created_at,user_id').eq('product_sku',p.sku).eq('approved',true).order('created_at',{ascending:false}).limit(8);const avg=reviews?.length?(reviews.reduce((a,r)=>a+Number(r.rating),0)/reviews.length):0;w.querySelector('.odo-review-stars').textContent=avg?`${stars(Math.round(avg))} ${avg.toFixed(1)}`:'No reviews yet';w.querySelector('.odo-review-count').textContent=reviews?.length?`${reviews.length} review${reviews.length===1?'':'s'}`:'Be the first to review';const list=w.querySelector('.odo-review-list');list.innerHTML=(reviews||[]).map(r=>`<div class="odo-review"><div class="odo-review-head"><span class="odo-review-name">ODO CUSTOMER</span><span class="odo-review-verified">VERIFIED PURCHASE</span></div><div class="odo-review-stars">${stars(r.rating)}</div><div class="odo-review-text">${esc(r.review_text||'')}</div></div>`).join('');const {data:{session}}=await sb.auth.getSession();const form=w.querySelector('.odo-review-form');if(!session){form.innerHTML+=`<button class="odo-review-btn" type="button" data-login>LOGIN TO REVIEW →</button>`;form.querySelector('[data-login]').onclick=()=>document.getElementById('odoAccountBtn')?.click();return}const {data:can}=await sb.rpc('odo_can_review_product',{p_sku:p.sku,p_user_id:session.user.id});if(!can){form.innerHTML+='<div class="odo-review-note">Once your order is delivered, you can leave a verified review here.</div>';return}const {data:existing}=await sb.from('product_reviews').select('id,rating,review_text').eq('product_sku',p.sku).eq('user_id',session.user.id).maybeSingle();form.innerHTML=`<label style="display:block;margin-top:10px;font-size:.54rem;color:#aaa">RATING<select data-rating>${[5,4,3,2,1].map(n=>`<option value="${n}" ${existing?.rating===n?'selected':''}>${n} / 5 · ${stars(n)}</option>`).join('')}</select></label><label style="display:block;margin-top:10px;font-size:.54rem;color:#aaa">YOUR REVIEW<textarea data-text placeholder="Tell other customers what you think…">${esc(existing?.review_text||'')}</textarea></label><button class="odo-review-btn" type="button" data-save>${existing?'UPDATE REVIEW':'SUBMIT REVIEW →'}</button>`;form.querySelector('[data-save]').onclick=async()=>{const payload={product_sku:p.sku,user_id:session.user.id,rating:Number(form.querySelector('[data-rating]').value),review_text:form.querySelector('[data-text]').value.trim(),approved:false,updated_at:new Date().toISOString()};let res=existing?await sb.from('product_reviews').update(payload).eq('id',existing.id):await sb.from('product_reviews').insert(payload);if(res.error){alert(res.error.message);return}alert('Thanks! Your review is awaiting approval.');load(w,p)}}
function boot(){styles();document.querySelectorAll('#odoLiveCatalog article.product, .streetwear-products article.product').forEach(card=>{const sku=card.querySelector('.product-number')?.textContent?.split('/')[0]?.trim();if(sku)mount(card,{sku})})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
setTimeout(boot,1500);
